=== FreeBSD Core Team

Link +
link:https://www.freebsd.org/administration/#t-core[FreeBSD Core Team] URL: https://www.freebsd.org/administration/#t-core[https://www.freebsd.org/administration/#t-core] +
Contact: FreeBSD Core Team <core@FreeBSD.org>

The FreeBSD Core Team is the governing body of FreeBSD.

==== Core Team Charter

A delegation of the current Team is working together with some members of the previous Team to draft a Core Team charter.
There was a face-to-face meeting in the US on December 3 - 4 to discuss the new Charter.
The same delegation also met with The FreeBSD Foundation Board on December 5th to discuss the collaboration details.
The delegation will present to the rest of the Team and discuss the details in the first quarter of 2023.

==== Experimental Matrix IM solution

The Team is working on evaluating Matrix as an instant messaging tool for the project.
This will make the project's communication channels less dependant on third parties.
The service will be made available to the FreeBSD community to test and evaluate its validity at a later date.

https://matrix.org/

==== Committer's Guide

Deprecate BSD-2-Clause-FreeBSD and use BSD-2-Clause.
For more information please refer to the link:https://cgit.freebsd.org/doc/commit/?id=a6e5d24925949785122a9f37f163d58239fd5484[commit].

=== Commit bits

* Core approved the src commit bit for Zhenlei Huang (zlei@).
* Core approved the src commit bit for Corvin Köhne (corvink@).
* Core approved the src commit bit for Sumit Saxon (ssaxena@).
* Core approved the restore of the source commit bit for Paweł Jakub Dawidek (pjd@).
